[server]
headless = true
address = "0.0.0.0"
port = 5001
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#A88A57"
backgroundColor = "#212F3C"
secondaryBackgroundColor = "#36404A"
